### PR TITLE
fix: add cors and change response to exactly what website expects

### LINKED ISSUE #26: Needs CORs support
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

_No response_

### PR DESCRIPTION
**Pull request by xkal36**
Closes #26 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing

**Comment by xkal36** [comment]
> CI is failing

passing now

**Comment by mcollina** [comment]
it seems to still be failing

**Comment by xkal36** [comment]
> it seems to still be failing

What part exactly?

**Comment by mcollina** [comment]
image

Unsure what that is.

**Comment by climba03003** [comment]
> > it seems to still be failing
> 
> What part exactly?

It is strange that the `Check linked issues` CI duplicated multiple times and it only success one amount of them. 
```
    *** ACTION RUN - START ***
    

Error: No linked issues found. Please add the corresponding issues in the pull request description.

    *** ACTION RUN - END ***
```

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
